networks:
  dto-red:
    ipam:
      driver: default
      config:
        - subnet: "172.28.0.0/16"
          
services:
  omdb:
    image: mysql:latest
    container_name: ombase_datos
    environment:
      MYSQL_DATABASE: Openmind
      #- MYSQL_ROOT_PASSWORD=db_password
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_password
    command: --log-bin-trust-function-creators=1
    secrets:
      - db_password      
    ports:
      - 3307:3306
    volumes:
      - ./mysql:/var/lib/mysql
      - ./db_dump:/docker-entrypoint-initdb.d
    networks:
      dto-red:
        ipv4_address: "172.28.0.10"
  omphpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: omphpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_HOST=omdb
      - PMA_PORT=3306
    networks:
      dto-red:
        ipv4_address: "172.28.0.11"
  omwebdatos:
    container_name: omweb_datos
    volumes:
      - ./datos/src:/var/www/html/src
      - ./datos/public:/var/www/html/public
    build:
      context: .
      dockerfile: ./datos/Dockerfile
    ports:
      - 8000:80
    depends_on:
      - omdb
    networks:
      dto-red:
        ipv4_address: "172.28.0.12"

  omwebnegocio:
    container_name: omweb_negocio
    volumes:
      - ./negocio/src:/var/www/html/src
      - ./negocio/public:/var/www/html/public
    build:
      context: .
      dockerfile: ./negocio/Dockerfile
    ports:
      - 9000:80
    depends_on:
      - omwebdatos
    networks:
      dto-red:
        ipv4_address: "172.28.0.13"
secrets:
  db_password:
    file: ./db_password.txt
    

volumes:
  db_dump:
  mysql:
  omdatos:
  omwebdatos:
  omwebnegocio:
