
@uriCurso = http://localhost:8000/api/curso

POST {{uriCurso}}
Content-Type: application/json

{
    "titulo": "Curso de creación de cursos",
    "descripcion": "Acá aprenderemos a crear cursos",
    "creador_id": "2",
    "fecha_inicio": "2025-07-02",
    "cupo": 0
}

###

GET {{uriCurso}}/2

###
PUT {{uriCurso}}/2
Content-Type: application/json

{
    "titulo": null,
    "descripcion": null,
    "creador_id": null,
    "fecha_inicio": null,
    "cupo": 1
}

###

DELETE {{uriCurso}}/1