
@uriCurso = http://localhost:9000/api/curso

POST {{uriCurso}}
Content-Type: application/json

{
    "titulo": "Curso de creación de cursos",
    "descripcion": "Acá aprenderemos a crear cursos",
    "creador_id": 2,
    "fecha_inicio": "2025-07-02",
    "semanas_duracion": 8,
    "categoria": "Backend",
    "nivel": "Intermedio",
    "cupo": 20
}

###

GET {{uriCurso}}/1

###
PUT {{uriCurso}}/2
Content-Type: application/json

{
    "titulo": "Curso de creación de cursos",
    "descripcion": "Acá aprenderemos a crear cursos",
    "creador_id": 2,
    "fecha_inicio": "2025-07-02",
    "semanas_duracion": 8,
    "categoria": "Backend",
    "nivel": "Intermedio",
    "cupo": 20
}

###

DELETE {{uriCurso}}/1