
@uriMatricula = http://localhost:9000/api/matricula
@token = Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjEsImVtYWlsIjoibHVpc0BnbWFpbC5jb20iLCJub21icmUiOiJMdWlzIExvcGV6IiwiaWF0IjoxNzUxODY3Nzk3LCJleHAiOjE3NTE4NjgzOTcsInJlZiI6dHJ1ZX0.q_3ZTb__bFEDxxW4lcZTxunPpnyDQ-YnV03MKFdMKjs

POST {{uriMatricula}}/1
Content-Type: application/json
Authorization: {{token}}

{
    "idUsuario": "2"
}

###

GET  {{uriMatricula}}?idUsuario=4
Authorization: {{token}}

###
PUT {{uriMatricula}}/1
Content-Type: application/json

{
    "idUsuario": null,
    "idCurso": 2,
    "fecha_matricula": null
}

###

DELETE {{uriMatricula}}
Authorization: {{token}}
Content-Type: application/json

{
  "idUsuario": "4",
  "idCurso": "1"
}