
@uriMatricula = http://localhost:8000/api/matricula
@token = Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjMsImVtYWlsIjoibHVpc0BnbWFpbC5jb20iLCJub21icmUiOiJMdWlzIExvcGV6IiwiaWF0IjoxNzUxODUzMTMzLCJleHAiOjE3NTE4NTM3MzMsInJlZiI6dHJ1ZX0.E7Mrpa5P-a7ECLr1N97HEYB6vpT9LT9qT9yVdR5EGSQ

POST {{uriMatricula}}/1
Content-Type: application/json
Authorization: {{token}}

{
    "idUsuario": "5"
}

###

GET  {{uriMatricula}}?idCurso=1
Authorization: {{token}}

###
PUT {{uriMatricula}}/1
Content-Type: application/json

{
    "idUsuario": null,
    "idCurso": 2,
    "fecha_matricula": null
}

###

DELETE {{uriMatricula}}/1