@uriUsuario = http://localhost:9000/api/usuario
@token = Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjQsImVtYWlsIjoiY2FtaWlAZ21haWwuY29tIiwibm9tYnJlIjoiQ2FtaWxhIExvcmlhIiwiaWF0IjoxNzUxODY0MDI4LCJleHAiOjE3NTE4NjQ2MjgsInJlZiI6dHJ1ZX0.YGPFmqc7Vi8XzTi2pAiZ5QZiTT9HBC4zxf2Bx6F0izQ

POST {{uriUsuario}}
Content-Type: application/json
Authorization: {{token}}

{
  "nombre": "Johan Loria",
  "email": "johan@gmail.com",
  "password": "1234"
}

###

GET {{uriUsuario}}/4
Authorization: {{token}}
###
PUT {{uriUsuario}}/3
Content-Type: application/json
Authorization: {{token}}

{
  "nombre": "Johan Espinoza",
  "email": null
}

###

DELETE {{uriUsuario}}/3
Authorization: {{token}}